PAYMENT_TYPE_LOAN = "loan"
PAYMENT_TYPE_ADVANCE = "advance"
PAYMENT_TYPE_PAYMENT_ORDER = "payment_order"
PAYMENT_TYPE_PROCUREMENT = "procurement"

EMPLOYEE_FINANCIAL_TYPES = frozenset({PAYMENT_TYPE_LOAN, PAYMENT_TYPE_ADVANCE})
EXTERNAL_PAYMENT_TYPES = frozenset({PAYMENT_TYPE_PAYMENT_ORDER, PAYMENT_TYPE_PROCUREMENT})
